version: "3"
services:
  da-ti-tong:
    image: da-ti-tong
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: da-ti-tong
    restart: "always"
    ports:
      - "8080:8080"
    networks:
      - dtt_net
    depends_on:
      - mysql
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /service/nginx/html/:/usr/share/nginx/html
      - /service/nginx/conf.d:/etc/nginx/conf.d
      - /service/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dtt_net
    restart: "always"
    container_name: nginx
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: mysql
    restart: "always"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "datitong2023*"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: 'datitong'
      MYSQL_PASSWORD: 'datitong2023*'
    volumes:
      - /service/mysql/conf.d:/etc/mysql/conf.d
      - /service/mysql/my.cnf:/etc/mysql/my.cnf
      - /service/mysql/data:/var/lib/mysql
      - /service/mysql/logs:/logs
    networks:
      - dtt_net
    command: --default-authentication-plugin=mysql_native_password
networks:
  dtt_net: